from __future__ import annotations

import csv
import json
import re
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'packages/server/migrations/002_seed_countries.sql'
SOURCE_URL = 'https://download.geonames.org/export/dump/countryInfo.txt'
SKIP_ISO2_CODES = {'AN', 'CS'}


def slugify(value: str) -> str:
    value = value.lower().strip()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-+", "-", value).strip('-')
    return value


def sql_text(value: str | None) -> str:
    if value is None:
        return 'NULL'
    return "'" + value.replace("'", "''") + "'"


def sql_array(values: list[str]) -> str:
    escaped = ','.join('"' + value.replace('"', '\\"') + '"' for value in values if value)
    return f"'{{{escaped}}}'"


def sql_json(value: dict) -> str:
    return sql_text(json.dumps(value, separators=(',', ':')))


def main() -> None:
    rows = []
    with urlopen(SOURCE_URL) as response:
      text = response.read().decode('utf-8')
    for line in text.splitlines():
        if not line or line.startswith('#'):
            continue
        row = [value.strip() for value in next(csv.reader([line], delimiter='\t'))]
        if row[0] in SKIP_ISO2_CODES:
            continue
        rows.append(row)

    statements = [
        '-- Generated by scripts/build_country_seed_sql.py',
        'INSERT INTO countries (',
        '  iso2, iso3, iso_numeric, fips_code, name, slug, capital, continent_code, tld, currency_code, currency_name,',
        '  phone_prefix, postal_code_format, postal_code_regex, languages, geoname_id, neighbors, area_km2, population, raw_source',
        ') VALUES',
    ]

    values_sql = []
    for row in rows:
        iso2, iso3, iso_numeric, fips_code, name, capital, area_km2, population, continent_code, tld, currency_code, currency_name, phone_prefix, postal_code_format, postal_code_regex, languages, geoname_id, neighbors = row[:18]
        language_list = [value for value in languages.split(',') if value]
        neighbor_list = [value for value in neighbors.split(',') if value]
        source_payload = {
            'source': 'geonames-countryInfo',
            'iso2': iso2,
            'iso3': iso3,
            'continentCode': continent_code,
        }
        values_sql.append(
            '  (' + ', '.join([
                sql_text(iso2),
                sql_text(iso3),
                sql_text(iso_numeric),
                sql_text(fips_code),
                sql_text(name),
                sql_text(slugify(name)),
                sql_text(capital or None),
                sql_text(continent_code or None),
                sql_text(tld or None),
                sql_text(currency_code or None),
                sql_text(currency_name or None),
                sql_text(phone_prefix or None),
                sql_text(postal_code_format or None),
                sql_text(postal_code_regex or None),
                sql_array(language_list),
                geoname_id or 'NULL',
                sql_array(neighbor_list),
                area_km2 or 'NULL',
                population or 'NULL',
                sql_json(source_payload) + '::jsonb',
            ]) + ')'
        )

    statements.append(',\n'.join(values_sql))
    statements.append('ON CONFLICT (iso2) DO UPDATE SET')
    statements.append('  iso3 = EXCLUDED.iso3,')
    statements.append('  iso_numeric = EXCLUDED.iso_numeric,')
    statements.append('  fips_code = EXCLUDED.fips_code,')
    statements.append('  name = EXCLUDED.name,')
    statements.append('  slug = EXCLUDED.slug,')
    statements.append('  capital = EXCLUDED.capital,')
    statements.append('  continent_code = EXCLUDED.continent_code,')
    statements.append('  tld = EXCLUDED.tld,')
    statements.append('  currency_code = EXCLUDED.currency_code,')
    statements.append('  currency_name = EXCLUDED.currency_name,')
    statements.append('  phone_prefix = EXCLUDED.phone_prefix,')
    statements.append('  postal_code_format = EXCLUDED.postal_code_format,')
    statements.append('  postal_code_regex = EXCLUDED.postal_code_regex,')
    statements.append('  languages = EXCLUDED.languages,')
    statements.append('  geoname_id = EXCLUDED.geoname_id,')
    statements.append('  neighbors = EXCLUDED.neighbors,')
    statements.append('  area_km2 = EXCLUDED.area_km2,')
    statements.append('  population = EXCLUDED.population,')
    statements.append('  raw_source = EXCLUDED.raw_source,')
    statements.append('  updated_at = NOW();')
    OUT.write_text('\n'.join(statements) + '\n', encoding='utf-8')
    print(f'wrote {len(rows)} country rows to {OUT}')


if __name__ == '__main__':
    main()
